# Generated by Django 2.1.4 on 2018-12-16 16:31

from django.db import migrations, models
import help_tools.qiniuTool


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pictextcommon',
            name='pic_url',
        ),
        migrations.AddField(
            model_name='pictextcommon',
            name='pic_file',
            field=models.ImageField(default=1, help_text='图片链接地址', upload_to=help_tools.qiniuTool.getFileUrl, verbose_name='图片链接地址'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pictextcommon',
            name='update_time',
            field=models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='pictextcommon',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='pictextcommon',
            name='words_result_num',
            field=models.IntegerField(default=0, help_text='文本行数', verbose_name='文本行数'),
        ),
    ]
