# Generated by Django 2.1.4 on 2018-12-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0002_auto_20181217_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictextcommon',
            name='language_type',
            field=models.CharField(choices=[('中英', 'CHN_ENG'), ('英文', 'ENG'), ('葡萄牙语', 'POR'), ('法语', 'FRE'), ('德语', 'GER'), ('意大利语', 'ITA'), ('西班牙语', 'SPA'), ('俄语', 'RUS'), ('日语', 'JAP'), ('韩语', 'KOR')], help_text='语言选择', max_length=20, verbose_name='语言选择'),
        ),
    ]
