# Generated by Django 2.1.4 on 2018-12-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0003_auto_20181217_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictextcommon',
            name='language_type',
            field=models.CharField(choices=[('CHN_ENG', '中英'), ('ENG', '英文'), ('POR', '葡萄牙语'), ('FRE', '法语'), ('GER', '德语'), ('ITA', '意大利语'), ('SPA', '西班牙语'), ('RUS', '俄语'), ('JAP', '日语'), ('KOR', '韩语')], help_text='语言选择', max_length=20, verbose_name='语言选择'),
        ),
    ]
