# Generated by Django 2.1.4 on 2018-12-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('female', '女'), ('other', '你猜'), ('male', '男')], help_text='性别', max_length=6, verbose_name='性别'),
        ),
    ]
