# Generated by Django 2.1.4 on 2018-12-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181212_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='add_time',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('male', '男'), ('female', '女'), ('other', '你猜')], help_text='性别', max_length=6, verbose_name='性别'),
        ),
    ]
