# Generated by Django 2.1.4 on 2018-12-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20181212_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.FileField(blank=True, help_text='头像', null=True, upload_to='', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('other', '你猜'), ('male', '男'), ('female', '女')], default='other', help_text='性别', max_length=6, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.IntegerField(blank=True, help_text='电话', null=True, verbose_name='电话'),
        ),
    ]
