# Generated by Django 2.1.4 on 2018-12-15 17:00

from django.db import migrations, models
from help_tools import qiniuTool


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20181212_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.FileField(blank=True, help_text='头像', null=True, upload_to=qiniuTool.getFileUrl, verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('female', '女'), ('male', '男'), ('other', '你猜')], default='other', help_text='性别', max_length=6, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.BigIntegerField(blank=True, help_text='电话', max_length=11, null=True, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='verifyphonecode',
            name='mobile',
            field=models.BigIntegerField(help_text='电话', max_length=11, verbose_name='电话'),
        ),
    ]
