# Generated by Django 2.1.4 on 2018-12-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20181216_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('other', '你猜'), ('female', '女'), ('male', '男')], default='other', help_text='性别', max_length=6, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='score',
            field=models.IntegerField(default=100, help_text='积分', verbose_name='积分'),
        ),
    ]
