# Generated by Django 2.1.4 on 2018-12-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20181216_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('female', '女'), ('male', '男'), ('other', '你猜')], default='other', help_text='性别', max_length=6, verbose_name='性别'),
        ),
    ]
